//
//  PlaybackStateReducer.swift
//  CorePlayerEngine
//
//  Created by builder on 9/18/26.
//

import Foundation

/// Deterministic state machine for a single playback session.
///
/// The reducer has no AVFoundation dependency and performs no I/O.
/// It only translates logical playback events into authoritative state.
///
/// This makes the state machine:
/// - deterministic
/// - independently testable
/// - independent of player implementation
/// - safe to reuse with AVFoundation or another backend
public struct PlaybackStateReducer: Sendable {

    public enum Event: Sendable {

        case reset
        case released

        case loadStarted
        case ready

        case play
        case pause

        case bufferingStarted
        case bufferingEnded

        case playbackCompleted

        case networkLost
        case networkRestored

        case failed(PlayerError)

        /// Synthetic event generated by a future PlaybackWatchdog.
        case watchdogExpired
    }

    private(set) public var state: PlayerState = .idle

    /// Whether playback should automatically resume after
    /// buffering/network recovery.
    private var resumeAfterInterruption = false

    public init(
        initialState: PlayerState = .idle
    ) {
        self.state = initialState
    }

    @discardableResult
    public mutating func reduce(
        _ event: Event
    ) -> PlayerState {

        switch event {

        // MARK: - Lifecycle

        case .reset, .released:
            state = .idle
            resumeAfterInterruption = false

        case .loadStarted:
            // Loading a new source is a lifecycle reset regardless
            // of the previous playback state.
            state = .loading
            resumeAfterInterruption = false

        case .ready:
            guard state == .loading else {
                return state
            }

            state = .ready

        // MARK: - Playback

        case .play:
            guard state.isPlayable else {
                return state
            }

            state = .playing
            resumeAfterInterruption = true

        case .pause:
            guard state == .playing ||
                    state == .buffering ||
                    state == .reconnecting
            else {
                return state
            }

            state = .paused
            resumeAfterInterruption = false

        // MARK: - Buffering

        case .bufferingStarted:
            guard state == .playing ||
                    state == .ready ||
                    state == .paused
            else {
                return state
            }

            if state == .playing {
                resumeAfterInterruption = true
            } else if state == .paused {
                resumeAfterInterruption = false
            }

            state = .buffering

        case .bufferingEnded:
            guard state == .buffering else {
                return state
            }

            state = resumeAfterInterruption
                ? .playing
                : .ready

        // MARK: - Completion

        case .playbackCompleted:
            guard state == .playing ||
                    state == .paused
            else {
                return state
            }

            state = .ended
            resumeAfterInterruption = false

        // MARK: - Network

        case .networkLost:
            guard state == .loading ||
                    state == .ready ||
                    state == .playing ||
                    state == .paused ||
                    state == .buffering
            else {
                return state
            }

            if state == .playing ||
                state == .buffering
            {
                resumeAfterInterruption = true
            }

            state = .reconnecting

        case .networkRestored:
            guard state == .reconnecting else {
                return state
            }

            state = resumeAfterInterruption
                ? .buffering
                : .ready

        // MARK: - Failure

        case .failed(let error):
            state = .error(error)
            resumeAfterInterruption = false

        // MARK: - Watchdog

        case .watchdogExpired:
            guard state == .buffering ||
                    state == .reconnecting
            else {
                return state
            }

            state = .error(.playbackStalled)
            resumeAfterInterruption = false
        }

        return state
    }

    public var shouldResumeAfterInterruption: Bool {
        resumeAfterInterruption
    }
}
